version: "3.8"
services:
  db:
    container_name: "postgres"
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - backend


  alembic:
    image: my-alembic-image
    build:
      context: .
    env_file:
      - .env  # Указывает на .env файл в текущей директории
    command: ./wait-for-it.sh db:5432 -- alembic upgrade head
    depends_on:
      - db
    networks:
      - backend


  fastapi:
    container_name: "fastapi"
    build:
      context: .
      dockerfile: Dockerfile
    command:  uvicorn app.main:app --reload --host ${WEBAPP_HOST} --port ${WEBAPP_PORT}
    ports:
      - ${WEBAPP_PORT}:${WEBAPP_PORT}
    restart: always
    depends_on:
      - db
      - alembic
    volumes:
      - .:/code
    working_dir: /code
    env_file:
      - .env  # Указывает на .env файл в текущей директории
    networks:
      - backend


#  redis:
#    image: redis:7
#    container_name: redis
#    ports:
#      - "6379:6379"
#    command: [ "redis-server", "--bind", "redis", "--port", "6379" ]
#
#    restart: unless-stopped
#    networks:
#      - backend

#  celery_worker:
#    container_name: celery_worker
#    build:
#      context: .
#      dockerfile: Dockerfile
#    command: [ "celery", "-A", "app.celery_app", "worker", "--loglevel=info" ]
#    restart: always
#    depends_on:
#      - redis
#      - fastapi
#      - db
#    working_dir: /code
#    volumes:
#      - .:/code
#    env_file:
#      - .env  # Указывает на .env файл в текущей директории
#    networks:
#      - backend
#
#  celery_beat:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: celery_beat
#    command: [ "celery", "-A", "app.celery_app", "beat", "--loglevel=info" ]
#    depends_on:
#      - redis
#      - fastapi
#      - db
#    working_dir: /code
#    volumes:
#      - .:/code
#    env_file:
#      - .env  # Указывает на .env файл в текущей директории
#    networks:
#      - backend

networks:
  backend:
    driver: bridge