version: "3.8"
services:
  db:
    container_name: "postgres"
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - backend

  alembic:
    image: my-alembic-image
    build:
      context: .
    env_file:
      - .env  # Указывает на .env файл в текущей директории
    command: ./wait-for-it.sh db:5432 -- alembic upgrade head
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - backend


  fastapi:
    container_name: "fastapi"
    build:
      context: .
      dockerfile: Dockerfile
    command:  uvicorn app.main:app --reload --host ${WEBAPP_HOST} --port ${WEBAPP_PORT}

    ports:
      - ${WEBAPP_PORT}:${WEBAPP_PORT}
    depends_on:
      - db
      - alembic
    volumes:
      - .:/code

    networks:
      - backend


#  bot:
#    container_name: aiogram-bot
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: aiogram-bot:latest
#    restart: unless-stopped
#    env_file:
#      - .env
#    environment:
#      BOT_TOKEN: ${BOT_TOKEN}
#    volumes:
#      - .:/bot
#    command: python app/aiogram_run.py

#
#  cron_run:
#    container_name: "cron_run"
#    build: ./crontab
#    command: cron -n
#    depends_on:
#      - bot
#    networks:
#      - backend

networks:
  backend:
    driver: bridge