"""add schedule_id to habit

Revision ID: 6ac223fe2160
Revises: 86647166a463
Create Date: 2025-04-29 16:48:41.947092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ac223fe2160'
down_revision: Union[str, None] = '86647166a463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('schedule_id', sa.Integer(), nullable=True))
    op.alter_column('habits', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('habits', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.create_foreign_key(None, 'habits', 'user_schedules', ['schedule_id'], ['id'])
    op.drop_column('habits', 'reminder_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('reminder_time', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'habits', type_='foreignkey')
    op.alter_column('habits', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('habits', 'description',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('habits', 'schedule_id')
    # ### end Alembic commands ###
